


spring:
  datasource:
    url: jdbc:h2:mem:cosdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
